config/routes.rb
Academia::Application.routes.draw do

  devise_for :users

  resources :statuses

  resources :service_types do
    member do
      get 'index'
    end
  end
 
  resources :dashboard do 
    collection do
      get :eligibility
    end
  end
 
  root :to => 'dashboard#index'

  get 'eligibility', :to => 'dashboard#eligibility'
  
  resources :patients do
  	collection do
      post 'apis_eligibility'
  		post 'search_data'
      post 'sign_in_api'
      post 'access_token'
      post 'verify_credentials'
      post 'import'
      post 'import_mapping'
      post 'authenticate_token'
      get 'transaction_logs'
      get 'delete_all'
  	end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def new
  	require 'headless'
    require "selenium-webdriver"

    head = Headless.new
    head.start

    driver = Selenium::WebDriver.for :firefox
    driver.navigate.to "https://cignaforhcp.cigna.com/web/secure/chcp/windowmanager#tab-hcp.pg.patientsearch$1"

    username = driver.find_element(:name, 'username')
    username.send_keys "skedia105"

    password = driver.find_element(:name, 'password')
    password.send_keys "Empclaims100"

    element = driver.find_element(:id, 'button1')
    # element.send_keys "Empclaims100"
    element.submit
    # driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    sleep(3)
    #tab-hcp.pg.patientsearch
    href_search = driver.find_elements(:class,'patients')
    href_search[1].click
    sleep(1)
    member_id = driver.find_element(:name, 'memberDataList[0].memberId')
    member_id.send_keys params[:patient][:patient_id]

    dob = driver.find_element(:name, 'memberDataList[0].dobDate')
    dob.send_keys params[:patient][:dob]

    first_name = driver.find_element(:name, 'memberDataList[0].firstName')
    first_name.send_keys params[:patient][:first_name]

    last_name = driver.find_element(:name, 'memberDataList[0].lastName')
    last_name.send_keys params[:patient][:last_name]


    ee = driver.find_elements(:class,'btn-submit-form-patient-search')[0]
    ee.submit

    sleep(3)
    link = driver.find_elements(:class,'oep-managed-link')[5]
    link.click
    sleep(3)
    # puts driver.title
    tables = driver.find_elements(:class,'collapseTable')
    @table1 = tables[0].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table2 = tables[1].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table3 = tables[2].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table4 = tables[3].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table5 = tables[4].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table6 = tables[5].attribute('innerHTML').gsub("\t","").gsub("\n","")

    driver.quit
    head.destroy

  end

  def index
    @patients = Patient.order('first_name asc')
  end

  def eligibility
    @service_types = EligibilityApi.new.service_type_codes
    @procedure_codes = EligibilityApi.new.procedure_codes
  end
end

# $("<img>").attr({'id':'img1','style':'margin-top:6%;','src':'http://loadinggif.com/images/image-selection/32.gif'}).appendTo('#innersec');

app/views/dashboard/eligibility.html.erb
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>

<div class="container well signin-form">
	<h3>	Member Info </h3>
	<br>
	  	<div class='row'>
			  <div class="col-md-2">
			  		<%= label_tag :first_name, 'First Name', :class => '' %>
					<%= text_field_tag :first_name, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>
			  <div class="col-md-2">
					<%= label_tag :last_name, 'Last Name', :class => '' %>
					<%= text_field_tag :last_name, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>

			  <div class="col-md-2">
					<%= label_tag :dob, 'DOB', :class => 'control-label' %>
					<%= text_field_tag :dob, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>

			  <div class="col-md-2">
					<%= label_tag :ins_id, 'Ins ID', :class => 'control-label' %>
					<%= text_field_tag :ins_id, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>

			  <div class="col-md-2">
					<%= label_tag :group_no, 'Group no', :class => 'control-label' %>
					<%= text_field_tag :group_no, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>
		</div>
		<h3>	Provider Info </h3>
		<br>
		<div class='row'>
			  <div class="col-md-2">
			  		<%= label_tag :p_first_name, 'First Name', :class => '' %>
					<%= text_field_tag :p_first_name, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>
			  <div class="col-md-2">
					<%= label_tag :p_last_name, 'Last Name', :class => '' %>
					<%= text_field_tag :p_last_name, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>

			  <div class="col-md-2">
					<%= label_tag :p_npi, 'NPI', :class => 'control-label' %>
					<%= text_field_tag :p_npi, nil, :class =>'form-control', :placeholder => 'Enter text' %>
			  </div>
		</div>

	</div>
	
<div class="container well">

			<h4>Patients Detail</h4>
		<div class="table-responsive">
			<table class="table table-striped">
			  <thead>
			    <tr>
			      <th>API name</th>
			      <th>Payer ID</th>
			      <th>Service Type</th>
			      <th>Procedure Code</th>
			      <th></th>
			      
			    </tr>
			  </thead>

			  <tbody>

			      <tr>

			        <td>Pokitdock Api</td>
			        <td><%= text_field_tag :payer_id, nil %></td>
			        <td><%= text_field_tag :service_type, nil %></td>
			        <td></td>
			        <td>
             		 	<%= form_tag apis_eligibility_patients_path, {:class => 'patient_pokit_form'} do %>
          					<%= hidden_field_tag :first_name,  "asd" %>
             		 		<%= hidden_field_tag :last_name, "asd" %>
             		 		<%= hidden_field_tag :dob, "asd" %>
             		 		<%= hidden_field_tag :ins_id, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :payer_id, "asd" %>
             		 		<%= hidden_field_tag :service_type, "asd" %>

             		 		<%= hidden_field_tag :type, "pokitdok" %>
             		 		
          					<%= submit_tag "Check", class: "btn btn-block btn-small btn-success" %>
         				<% end %>
			      	</td>
			      </tr>
			      <tr>

			        <td>Eligibility Api</td>
			        <td><%= text_field_tag :eligi_payer_id, nil %></td>
			        <td>
			        	<%= select_tag :eligi_service_type, options_for_select(@service_types) %>
			        	<%= select_tag :eligi_service_type, options_for_select(@service_types) %>
			        	<%= select_tag :eligi_service_type, options_for_select(@service_types) %>
			        	<%= select_tag :eligi_service_type, options_for_select(@service_types) %>
			        </td>
			        <td>
			        	<%= select_tag :eligi_procedure_code, options_for_select(@procedure_codes) %>
			        	<%= select_tag :eligi_procedure_code, options_for_select(@procedure_codes) %>
			        	<%= select_tag :eligi_procedure_code, options_for_select(@procedure_codes) %>
			        	<%= select_tag :eligi_procedure_code, options_for_select(@procedure_codes) %>
			        	<%= select_tag :eligi_procedure_code, options_for_select(@procedure_codes) %>
			        </td>

			        <td>
             		 	<%= form_tag apis_eligibility_patients_path, {:class => 'patient_eligi_form'} do %>
          					<%= hidden_field_tag :first_name,  "asd" %>
             		 		<%= hidden_field_tag :last_name, "asd" %>
             		 		<%= hidden_field_tag :dob, "asd" %>
             		 		<%= hidden_field_tag :ins_id, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :payer_id, "asd" %>
             		 		<%= hidden_field_tag :service_type, "asd" %>
             		 		<%= hidden_field_tag :service_type, "asd" %>
             		 		<%= hidden_field_tag :procedure_code, "asd" %>


             		 		<%= hidden_field_tag :p_first_name,  "asd" %>
             		 		<%= hidden_field_tag :p_last_name, "asd" %>
             		 		<%= hidden_field_tag :p_npi, "asd" %>

             		 		<%= hidden_field_tag :type, "eligibility" %>
             		 		
          					<%= submit_tag "Check", class: "btn btn-block btn-small btn-success" %>
         				<% end %>
			      	</td>
			      </tr>
			      <tr>

			        <td>Availity Api</td>
			        <td><%= text_field_tag :avi_payer_id, nil %></td>
			        <td><%= text_field_tag :avi_service_type, nil %></td>
			        <td></td>
			        <td>
             		 	<%= form_tag apis_eligibility_patients_path, {:class => 'patient_avi_form'} do %>
          					<%= hidden_field_tag :first_name,  "asd" %>
             		 		<%= hidden_field_tag :last_name, "asd" %>
             		 		<%= hidden_field_tag :dob, "asd" %>
             		 		<%= hidden_field_tag :ins_id, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :group_no, "asd" %>
             		 		<%= hidden_field_tag :payer_id, "asd" %>
             		 		<%= hidden_field_tag :service_type, "asd" %>
             		 		
             		 		<%= hidden_field_tag :customer_id, "388016" %>
             		 		<%= hidden_field_tag :username, "statpay" %>
             		 		<%= hidden_field_tag :pass, "Swervepay0!" %>
             		 		<%= hidden_field_tag :site_url, "https://apps.availity.com/" %>

             		 		<%= hidden_field_tag :p_first_name,  "asd" %>
             		 		<%= hidden_field_tag :p_last_name, "asd" %>
             		 		<%= hidden_field_tag :p_npi, "asd" %>

             		 		<%= hidden_field_tag :type, "availity" %>
             		 		
          					<%= submit_tag "Check", class: "btn btn-block btn-small btn-success" %>
         				<% end %>
			      	</td>
			      </tr>
			  </tbody>
			</table>
			</div>
			<br>
			<br><br>
</div>
<script type="text/javascript">


	$(document).ready(function(){
		
		$( ".patient_pokit_form" ).submit(function( event ) {
  		event.preventDefault();
  		console.log($(this).children('#first_name').val())
  		$(this).children('#first_name').val($('#first_name').val().trim())
  		$(this).children('#last_name').val($('#last_name').val().trim())
  		$(this).children('#dob').val($('#dob').val().trim())
  		$(this).children('#ins_id').val($('#ins_id').val().trim())
  		$(this).children('#group_no').val($('#group_no').val().trim())
  		$(this).children('#payer_id').val($('#payer_id').val().trim())
  		$(this).children('#service_type').val($('#service_type').val().trim())

			this.submit()
		});

		$( ".patient_avi_form" ).submit(function( event ) {
  		event.preventDefault();
  		console.log($(this).children('#first_name').val())
  		$(this).children('#first_name').val($('#first_name').val().trim())
  		$(this).children('#last_name').val($('#last_name').val().trim())
  		$(this).children('#dob').val($('#dob').val().trim())
  		$(this).children('#ins_id').val($('#ins_id').val().trim())
  		$(this).children('#group_no').val($('#group_no').val().trim())
  		$(this).children('#payer_id').val($('#avi_payer_id').val().trim())
  		$(this).children('#service_type').val($('#avi_service_type').val().trim())
  		$(this).children('#p_first_name').val($('#p_first_name').val().trim())
  		$(this).children('#p_last_name').val($('#p_last_name').val().trim())
  		$(this).children('#p_npi').val($('#p_npi').val().trim())

			this.submit()
		});

		$( ".patient_eligi_form" ).submit(function( event ) {
  		event.preventDefault();
  		
  		var st_values = []
  		$('select[name="eligi_service_type"]').each(function(e,v){
  			if(v.value != ''){
  				st_values.push(v.value)
  			}
  		})

  		var p_values = []
  		$('select[name="eligi_procedure_code"]').each(function(e,v){
  			if(v.value != ''){
  				p_values.push(v.value)
  			}
  		})

  		console.log($(this).children('#first_name').val())
  		$(this).children('#first_name').val($('#first_name').val().trim())
  		$(this).children('#last_name').val($('#last_name').val().trim())
  		$(this).children('#dob').val($('#dob').val().trim())
  		$(this).children('#ins_id').val($('#ins_id').val().trim())
  		$(this).children('#group_no').val($('#group_no').val().trim())
  		$(this).children('#payer_id').val($('#eligi_payer_id').val().trim())
  		$(this).children('#service_type').val(st_values)
  		$(this).children('#procedure_code').val(p_values)

  		$(this).children('#p_first_name').val($('#p_first_name').val().trim())
  		$(this).children('#p_last_name').val($('#p_last_name').val().trim())
  		$(this).children('#p_npi').val($('#p_npi').val().trim())

			this.submit()
		});
	})
</script>

app/views/dashboard/index.html.erb
<%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>

<div class="container well signin-form">
	<span class="pull-right">
		<%= link_to 'Visit Status Page', statuses_path  ,class: "text-danger"%>
	</span>
	<h3>	Sign In</h3>
	<br>
	<%= form_for Patient.new ,:html => { :class => 'form-inline signin' } do |f| %>
	  <div class="form-group">
	  		<%= label_tag :username, 'Username', :class => 'control-label' %>
			<%= f.text_field :username, :class =>'form-control', :placeholder => 'Credentials not saved' %>
	  </div>
	  <div class="form-group">
			<%= label_tag :password, 'Password', :class => 'control-label' %>
			<%= f.password_field :password, :class =>'form-control', :placeholder => 'Credentials not saved' %>
	  </div>

	  <div class="form-group">
			<%= label_tag "Website to Scrap data", "Website to Scrap data", :class=> 'control-label' %>
			<%= f.select :site_to_scrap, options_for_site,{} , {:class=> 'form-control'} %>
	  </div>
	  
		<%= submit_tag "", :value => "► check & save credentials", :class => "btn btn-sm btn-primary", id: 'submit-button' %>
		<div class="form-group">
			<%= label_tag "Service type", "Service type", :class=> 'control-label' %>
			<%= text_field_tag :serv_type, nil , {:class=> 'form-control'} %>
	  </div>
  <br>
	<% end %>
	</div>
	<div class="row">
		<div class="col-md-1">

		</div>
		<div class="well col-md-4 signup-form">
			<h4>Import Patients</h4>
			<br>
			<%= form_tag import_patients_path, multipart: true do %>
					<%= file_field_tag :file %><br />
					<%= submit_tag "Import Patients" ,:class => "btn btn-danger"%>
			<% end %>
		</div>

		<div class="col-md-1">

		</div>

		<div class="well col-md-4 signup-form">

			 <% id = Status.where(site_url: 'all').first.id %>

			<span class="pull-right">
			<%= link_to 'Download CSV', service_type_path(id)+".csv" ,class: "text-danger"%>
			</span>

			<h4>Import Service type mapping</h4>
			<br>
			<%=   form_tag import_mapping_patients_path(id), multipart: true do %>
					<%= file_field_tag :file %><br />
					<%= submit_tag "Import Service Type Mapping" ,:class => "btn btn-danger"%>
			<% end %>
	  </div>

	</div>
<%if !@patients.first.nil? %>
<div class="container well">

			<h4>Patients Detail</h4>
		<div class="table-responsive">
			<table class="table table-striped">
			  <thead>
			    <tr>
			      <th>First name</th>
			      <th>Last name</th>
			      <th>Patient</th>
			      <th>Date of birth</th>
			      <th colspan="3">    <%= link_to 'Delete All', delete_all_patients_path, data: { confirm: 'Are you sure?' }  ,class: "btn btn-xs btn-danger"%></th>
			    </tr>
			  </thead>

			  <tbody>

			    <% @patients.each do |patient,index| %>
			      <tr>

			        <!-- <td><%= index %></td> -->
			        <td><%= patient.first_name %></td>
			        <td><%= patient.last_name %></td>
			        <td><%= patient.patient_id %></td>
			        <td><%= patient.dob %></td>

			          <% if patient.record_available=='complete'%>
			           <td>
			            <%= form_for(patient) do %>
			          					<%= submit_tag "View", class: "btn btn-block btn-small btn-success" %>
			         				 <% end %>
			             <%elsif patient.record_available=='pending'%>
			             <td>
			          					<%= button_tag "Pending..", class: "btn btn-block btn-small btn-info" %>

			             <%elsif patient.record_available=='failed' %>
			             <td>
			             		 <%= form_for patient, :html => { :class => 'patient_form' } do |f| %>
			          					<%= f.hidden_field :username, value: "asd" %>
			             		 		<%= f.hidden_field :password, value: "asd" %>
			             		 		<%= f.hidden_field :serv_type, value: "asd" %>
			             		 		
			             		 		<%= f.hidden_field :site_to_scrap, value: "asd" %>
			          					<%= submit_tag "Re-Check", class: "btn btn-block btn-small btn-danger" %>
			         				 <% end %>

			             <%else%>
			             <td>
			             		 <%= form_for patient, :html => { :class => 'patient_form' } do |f| %>
			             		 		<%= f.hidden_field :username, value: "asd" %>
			             		 		<%= f.hidden_field :password, value: "asd" %>
			             		 		<%= f.hidden_field :serv_type, value: "asd" %>
			             		 		<%= f.hidden_field :site_to_scrap, value: "asd" %>
			          					<%= submit_tag "Check", class: "btn btn-block btn-small btn-warning" %>
			         				 <% end %>
 			           <%end %>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
			</div>
			<br>
			<br><br>
</div>
<%end%>
<script type="text/javascript">


	function fillup_signin_fields(){
		selected_val = $('#patient_site_to_scrap option:selected').val()

		if(session_arr[selected_val]) {
			$('#patient_username').val(session_arr[selected_val]['username'])
			$('#patient_password').val(session_arr[selected_val]['password'])
		}
		else {
			$('#patient_username').val("")
			$('#patient_password').val("")
		}
	}


	$(document).ready(function(){
		session_arr = <%= raw(session.to_json) %>

		setTimeout(function() { fillup_signin_fields(); }, 300);

		$('#patient_site_to_scrap').on('change', function(){
			fillup_signin_fields()
		})

		$( ".patient_form" ).submit(function( event ) {
  		event.preventDefault();
  		$(this).children('#patient_username').val($('#patient_username').val().trim())
  		$(this).children('#patient_password').val($('#patient_password').val().trim())
  		$(this).children('#patient_serv_type').val($('#serv_type').val().trim())
  		$(this).children('#patient_site_to_scrap').val($('#patient_site_to_scrap option:selected').val().trim())
			this.submit()
		});
	})
</script>