config/routes.rb
Academia::Application.routes.draw do

  devise_for :users

  resources :statuses

  resources :service_types do
    member do
      get 'index'
    end
  end
 
  resources :dashboard do 
    collection do
      get :eligibility
    end
  end
 
  root :to => 'dashboard#index'

  get 'eligibility', :to => 'dashboard#eligibility'
  
  resources :patients do
  	collection do
      post 'apis_eligibility'
  		post 'search_data'
      post 'sign_in_api'
      post 'access_token'
      post 'verify_credentials'
      post 'import'
      post 'import_mapping'
      post 'authenticate_token'
      get 'transaction_logs'
      get 'delete_all'
  	end
  end
end

app/controllers/statuses_controller.rb
require 'rake'

Rake::Task.clear # necessary to avoid tasks being loaded several times in dev mode
Academia::Application.load_tasks # providing your application name is 'sample'

class StatusesController < InheritedResources::Base

  # def edit
  #   @status = Status.find(params[:id])
  # end

  def edit
    flash[:warning] = "Test executed..."
  
    # status = Status.find(params[:id])
    url = Status.find(params[:id]).site_url
  
    if url.include? 'cignaforhcp'
      %x[rake cigna_test]
      # Rake::Task["cigna_test"].invoke
    elsif url.include? 'mhnet'
      %x[rake mhnet_test]
      # Rake::Task["mhnet_test"].invoke
    elsif url.include? 'availity'
      %x[rake availity_test]
      # Rake::Task["availity_test"].invoke
    end
  
    redirect_to :back
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
  def status_of_site(status_id)
    status = Status.find(status_id)
    status.status && status.login_status  && status.patient_search_status && status.site_status
  end
end

app/views/statuses/edit.html.erb
  <div class="col-md-6 col-md-offset-3">

    <h3>Verify your Previous Credintials</h3>
    <br />

    <%= form_tag do %>
      <%= label_tag(:p_un, "Previous Username") %>
      <%= text_field_tag 'p_un',nil ,class: 'form-control' %>

      <br />
      <%= label_tag(:p_pw, "Previous Password") %>
      <%= password_field_tag 'p_pw',nil ,class: 'form-control' %>

    <% end %>
    <br />


    <h3>Update your Credintials</h3>
    <br />
    <%= form_for(@status) do |f| %>

      <%= f.label :site_username %>
      <%= f.text_field :site_username, class: 'form-control' %>
      <br />
      <%= f.label :site_password %>
      <%= f.password_field :site_password, class: 'form-control' %>
      <br />
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>



<!--

<script>
s_un = <% raw(@status.site_username) %>
s_pw = <% raw(@status.site_password) %>

$('#p_pw').focusout(function a() {
  if ( $('#p_un').val() === s_un && $('#p_pw').val() === s_pw )
  {
    alert('msg');
  }
  else
  {
    alert('asdf')
  }

});
</script> -->

app/views/statuses/index.html.erb
<div class="show-list">
<h3>Status of websites</h3>
<br />

<table class="table">
  <tr>
    <th></th>
    <th>Site url</th>
    <th>Status</th>
    <th>Date checked</th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
<% if status.site_url!="all" %>
  <tr>
    <td> </td>
    <td><%= status.site_url %></td>
    <% if status.test_status_hash.empty? %>
    <td class="text-warning"><b> No test cases</b></td>
    <% elsif  status.test_status_hash["Site Status"] != "false" %>
    <td class="text-success"> Site is OK </td>
    <%else%>
    <td class="text-danger"> Tests are Failing </td>
    <%end%>
    <td><%= status.date_checked %></td>
    <td><%= link_to 'View Site Status', status, class: "btn btn-info" %></td>
  </tr>
  <%end%>
<% end %>
</table>
</div>

app/views/statuses/show.html.erb
<% if @status.site_url  != "all" %>

<br /><br /><br /><br />
<div class="row">
<div class="col-md-2">

</div>
<div class="col-md-8">


<div class="">

<p id="notice"><%= notice %></p>

<br ><br >
<p>
  <h3> Site Url: <%= @status.site_url %> </h3>
  <span style="display:none" class="pull-right">
    <%= link_to 'Change Credintials for test cases', edit_status_path , class: "btn btn-danger" %>
  </span>

  <span style="display:none" class="pull-right">

    <%= link_to 'Run Test Cases Again', edit_status_path, class: "btn btn-danger" %>
  </span>
  <br />
<%if @status.test_status_hash.present? %>    
  <table class="table table-striped">
    <thead>
      <tr>
        <th>
          Details of test
        </th>
        <th>

        </th>
        <th>
          Status
        </th>
        <th>
          Date &amp; Time
        </th>
      </tr>
    </thead>
    <tbody>

      <% @status.test_status_hash.each do |key,value| %>
      <tr>
        <th>
          <h5> <%= key %> </h5>
        <th>
        <td>
          <% if value != "false" %>
            <span class="text-info"><%= value %></span>
          <% else %>
            <span class="text-danger">Not Found</span>
          <% end %>
        </td>
        <td>
          <%= @status.date_checked.to_s(:long) %>
        </td>
      </tr>
      <%end %>
    </tbody>
  </table>
<% else %>
  <h3>No test cases </h3>
  <br>
<% end %>

<%= link_to 'Back', statuses_path %>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-3">

  </div>


  <div class="well col-md-6 signup-form">

    <span class="pull-right">
    <%= link_to 'Download CSV',  service_type_path(@status.id)+".csv" ,class: "text-danger"%>
    </span>

    <h4>Import Service type mapping</h4>
    <br>
    <%=   form_tag import_mapping_patients_path(@status.id), multipart: true do %>
        <%= file_field_tag :file %><br />
        <%= submit_tag "Import Service Type Mapping" ,:class => "btn btn-danger"%>
    <% end %>
  </div>
</div>
<% end %>